### ISSUE TITLE
Keeping Peter happy

### ISSUE THREAD

**Issue by Buneman** [tegola-hubs/tegola#1]
Need to set up port forwarding or whatever so that (a) people can see the webcam in my window and (b) so that I can configure a NS on the pole outside my house.  These are both on the 192.168.1.x subnet on the NS which is variously 10.2.0.202 or 10.11.11.2 or GKW when we reconfigure

Oh Yes, I'd also like to SSH easily to my desktop 192.168.1.2 which sometimes does useful data gathering.

**Comment by wwaites** [comment]
(a) webcam -- now lives at http://www.arnisdale.org/schoolhousecam/
Here is the apache config that does this:

```
ProxyRequests   off
ProxyPass   /schoolhousecam/ http://10.11.10.5/
ProxyHTMLURLMap http://10.11.10.5 /schoolhousecam
RedirectMatch   ^/schoolhousecam$ /schoolhousecam/
<Location /schoolhousecam/>
    ProxyPassReverse    /
    ProxyHTMLURLMap     / /schoolhouscam/
    SetOutputFilter INFLATE;DEFLATE
</Location>
<Proxy *>
    Order deny,allow
    Allow from all
</Proxy>
```

**Comment by wwaites** [comment]
ssh from outside. Port forwarding is messy because the default route on the end host tends to be the other SMO router. So packets come in one and go out the other. Therefore we have to both redirect the port _and_ do NAT on t1 so that the source appears to be t1 itself.

```
iptables -t nat -I PREROUTING -p tcp --dport 1022 --dst 194.35.194.250 -j DNAT --to-destination 10.11.10.2:22
iptables -t nat -I POSTROUTING 17 -p tcp --dport 22 --dst 10.11.10.2 -j MASQUERADE
```

The magic number of 17 is just before the rule on t1 that drops everything that appears to be coming from the outside destined for internal hosts.

So, to log in from outside, connect to port 1022 of t1.
